server:
  port: 8040
spring:
  application:
    name: auth-center
  cloud:
    nacos:
      discovery:
        server-addr: 129.211.159.145:8848
  datasource:
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.211.159.145:3306/pig

  redis:
    host: 129.211.159.145
    port: 6379
    password: zlq201799




