server:
  port: 8040
spring:
  application:
    name: auth-center
  cloud:
    nacos:
      discovery:
        server-addr: 129.211.159.145:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yml
        shared-dataids: application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  profiles:
    active: @profiles.active@
